### ISSUE TITLE
Only variables should be passed by reference

### ISSUE THREAD

**Issue by poliander** [neos/ldap#21]
Neos_Ldap_Service_BindProvider_ActiveDirectoryBind.php, line 58

Please change...

`array_pop(explode('\\', $username))`

...to...

```
$usernameSegments = explode('\\', $username);
array_pop($usernameSegments);
```

**Comment by radmiraal** [comment]
Hi @poliander , thanks for the report. Could you be so kind to open a PR for that? That's a bit easier to handle, there's an online edit feature in github you can easily use on https://github.com/neos/ldap/edit/master/Classes/Service/BindProvider/ActiveDirectoryBind.php

**Comment by kdambekalns** [comment]
Whatever… I obviously forgot to create a PR out my change last year… 🤷‍♂️

**Comment by poliander** [comment]
I don't care anymore

**Comment by kdambekalns** [comment]
Fair enough. I forgot about it, TBH.

I decided to just merge the PR. I am reluctant to roll a release, though, since I don't use the package myself.
