### ISSUE TITLE
Release Flow 6.x and 7.x compatible versions?

### ISSUE THREAD

**Issue by mrimann** [neos/ldap#30]
Will there be releases that are marked compatible with Flow 6.x and/or 7.x? (right now, composer.json denies installation in any installation newer than Flow 5.x)

- [x] #29 
- [ ] #31

**Comment by mrimann** [comment]
Looks like @GuangHa has already prepared a Pull Request: https://github.com/neos/ldap/pull/29

@albe  or @kdambekalns - is there anything missing (besides Flow 7.x compatibility) to merge/release new versions that are compatible with current Flow versions? This package is in use on several of our projects and having a current/compatible version would help us a lot!

**Comment by albe** [comment]
nothing from my side - I just can't really test this is working, so am fully dependent on confirmation by users of the package. If nothing speaks against it, I'm fine with merging #29 and tagging a release, then checking for Flow 7.x

**Comment by mrimann** [comment]
I've just checked in our VersionControl system if and where we're using the neos/ldap package - and as I see, we're running the official package with some Flow 5.x setups. And we also run the forked version that led to #29 in some Flow 6.3.x based installations. Since I'm not aware of any problems with those and already used some of those internal tools as a user (e.g. logged in with an LDAP user), I'd say "it seems to work".

**Comment by kdambekalns** [comment]
I left a review on #29. For Flow 7.0 this needs a change to use https://github.com/neos/flow-development-collection/pull/2134 instead (@albe knows… 😎)

**Comment by albe** [comment]
Merged #29 and tagged a 2.0.0 release - next would be 7.0 support which is another breaking release unfortunately (thanks for the hint @kdambekalns 😄), so will need a 3.0.0 release. Right now #31 is just based on theoretics, so needs some testing.
